require: rubocop-sketchup

inherit_from:
  - https://raw.githubusercontent.com/SketchUp/rubocop-sketchup/master/sketchup-style.yml
  - .rubocop-todo.yml

AllCops:
  Exclude:
    - src/*/vendor/**/*
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2014
    Exclude:
      - skippy/**/*
      - tests/**/*
      - Tools/**/*
  TargetRubyVersion: 2.2 # Should have been 2.0 but RuboCop dropped support.


# TODO: Migrate to Set
SketchupDeprecations/SketchupSet:
  Enabled: false


Layout/IndentHeredoc:
  Enabled: false

Layout/IndentationWidth:
  Exclude:
    - src/tt_cleanup.rb


# The error reporter needs to rescue Exception
Lint/RescueException:
  Enabled: false


Naming/ClassAndModuleCamelCase:
  Exclude:
    - Tests/**/*

Naming/FileName:
  Exclude:
    - Tests/**/*
    - Tools/DebugSketchUp.rb

Naming/MethodName:
  Exclude:
    - Tests/**/*

# TODO: Add these to sketchup-style.yml
Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - x
    - y
    - z
    - u
    - v

Naming/VariableNumber:
  Enabled: false


Style/NumericLiterals:
  Enabled: false

# TODO: Add these to sketchup-style.yml
Style/RedundantSelf:
  Enabled: false
